import Head from 'next/head'
import React, {FC, useEffect, useState} from 'react'
import axios from 'axios'
import AddIssueForm from '../components/addIssueForm/AddIssueForm'
import Header from '../components/header/Header'
import ShowFormBtn from '../components/button/ShowFormBtn'
import IssueList from '../components/issueList/IssueList'
import Footer from '../components/footer/Footer'
import { Issues } from '../model/model'

import styles from './Home.module.css'

const Home: FC = () => {
  const [issues, setIssues] = useState <Issues[]>([])
  const [showForm, setShowForm] = useState(false)

  useEffect(() => {
    getIssues();
  }, [issues])
  
  const getIssues = async () => {
    const res = await axios.get('https://fake-server-issue-tracker.herokuapp.com/tasks');
    const context = await res.data;
    context.sort((a: any, b: any) => {
      return a.status === b.status ? 0 : a.status ? -1 : 1;
    })
    context.sort((a: any, b: any) => {
      return a.complete === b.complete ? 0 : a.complete ? -1 : 1;
    })
    setIssues(context)
  }

  const handleShowForm = () => {
    setShowForm(!showForm)
  }

  return (
    <div>
      <Head>
        <title>Issue Tracker App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.header}>
          <Header />
          <ShowFormBtn showForm={showForm} handleShowForm={handleShowForm} />
        </div>
        
        {showForm && (
          <div>
            <AddIssueForm setShowForm={setShowForm} />
          </div>
        )}

        {issues.length === 0 && (
          <p className={styles.noIssues}>Click <span>Add Issue</span> to start adding issues!</p>
        )}

        <IssueList issues={issues} />
      </main>
      <Footer />
    </div>
  )
}

export default Home